### ISSUE TITLE
Signature type and length are missing in interest name

### ISSUE THREAD

**Issue by peurpdapeurp** [yoursunny/esp8266ndn#1]
Hello, there is a possible bug that the signed interests generated by the esp8266ndn library have an incorrect TLV encoding.

Two of the strange things about the TLV I found were this:
 1. There is no 0x17 (signature value type) or 0x22 (expected signature value length, 32 bytes) in the signed interest TLV generated by the esp8266ndn library
 2. The generic name component under which the signature value should be nested has an incorrect
length; the length indicates 32 bytes, but there are 36 bytes in that generic name component.

The exact error output from PyNDN2 was this:
```
Traceback (most recent call last):
  File "test_sign_verify_interest_hmac.py", line 114, in <module>
    main()
  File "test_sign_verify_interest_hmac.py", line 93, in main
    if KeyChain.verifyInterestWithHmacWithSha256(interest, key):
  File "build/bdist.linux-armv7l/egg/pyndn/security/key_chain.py", line 1364, in verifyInterestWithHmacWithSha256
  File "build/bdist.linux-armv7l/egg/pyndn/encoding/tlv_0_2_wire_format.py", line 505, in decodeSignatureInfoAndValue
RuntimeError: Did not get the expected TLV type
```

Below I have pasted an interest TLV that verifies correctly with PyNDN2, and the interest TLV generated by the esp8266ndn library that failed to verify because of a TLV unexpected type error.

This interest verifies correctly with PyNDN2:
```
TlvInterest = Blob(bytearray([
0x05, 0x47,   # NDN Interest
  0x07, 0x3f,  # Name
    0x08, 0x03, 0x6e, 0x64, 0x6e, # "ndn"
    0x08, 0x03, 0x61, 0x62, 0x63, # "abc"
    0x08, 0x0f,   # NameComponent
      0x16, 0x0d, # SignatureInfo
        0x1b, 0x01, 0x04, # SignatureType = SignatureHmacWithSha256
        0x1c, 0x08,   # KeyLocator
          0x07, 0x06, # Name
            0x08, 0x04, 0x6b, 0x65, 0x79, 0x31, # "key1"
    0x08, 0x22,   # NameComponent
      0x17, 0x20, # SignatureValue
        0x61, 0xe0, 0x60, 0x58, 0x1e, 0x2b, 0x75, 0x43, 0xf8, 0x8f,
        0xad, 0xa9, 0xdf, 0xa7, 0x6e, 0x43, 0x98, 0x5c, 0xc7, 0x3c,
        0x9b, 0x50, 0xf9, 0x8e, 0xc2, 0x3f, 0xd1, 0x70, 0x79, 0x4d,
        0xf1, 0xe8,
  0x0a, 0x04, 0xd1, 0x3c, 0x4b, 0x2f # Nonce
  ]))
```

This interest (generated by esp8266ndn library) does not verify correctly with PyNDN2:
```
TlvInterest = Blob(bytearray([
    0x05, 0x89, # NDN Interest 2
    0x07, 0x7D, # Name 2
      0x08, 0x0A, 0x63, 0x6F, 0x6E, 0x74, 0x72, 0x6F, 0x6C, 0x6C, 0x65, 0x72, # "controller" 12
      0x08, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, # "register" 10
      0x08, 0x0C, 0x00, 0x00, 0x00, 0x00, 0x60, 0x67, 0xFF, 0x3F, 0x78, 0x56, 0xAD, 0xBA, # "192.168.4.20" 14
      0x08, 0x0A, 0x45, 0x53, 0x50, 0x33, 0x32, 0x49, 0x44, 0x30, 0x30, 0x31, # "ESP32ID001" 12
      0x08, 0x29, # NameComponent 2
       0x16, 0x27, # SignatureInfo 2
         0x1B, 0x01, 0x04, # SignatureType = SignatureHmacWithSha256 3
         0x1C, 0x22, # KeyLocator 2
             0x1D, 0x20, # KeyDigest 2
                  0x63, 0x0D, 0xCD, 0x29, 0x66, 0xC4, 0x33, 0x66, 0x91, 0x12, # 10
                  0x54, 0x48, 0xBB, 0xB2, 0x5B, 0x4F, 0xF4, 0x12, 0xA4, 0x9C, # 10
                  0x73, 0x2D, 0xB2, 0xC8, 0xAB, 0xC1, 0xB8, 0x58, 0x1B, 0xD7, # 10
                  0x10, 0xDD, # 2
      0x08, 0x20, # Generic name component 2
         0x77, 0x7D, 0x34, 0xE8, 0xA5, 0x8F, 0x58, 0xB6, 0xBB, 0x9B, # 10
         0x7D, 0x30, 0x2A, 0x36, 0x45, 0xBE, 0x82, 0xCF, 0xAC, 0x5E, # 10
         0x83, 0x1A, 0x47, 0x1A, 0x93, 0xA4, 0x57, 0xC5, 0xCD, 0x19, # 10
         0x9B, 0xB6, 0x09, 0x02, 0x12, 0x00 # 6
    0x0A, 0x04, 0xD1, 0x4E, 0x3D, 0xE5 # Nonce 6
]))
```

**Comment by yoursunny** [comment]
> There is no 0x17 (signature value type) or 0x22 (expected signature value length, 32 bytes) in the signed interest TLV generated by the esp8266ndn library

This is a bug. [ndn-cxx's test case](https://github.com/named-data/ndn-cxx/blob/2b765f8ae73e204b8a9016361be7fe421ccbd5fd/tests/unit-tests/security/verification-helpers.t.cpp#L177-L189) encodes the last name component with `0x17 0x20` but this library's `Face` class did not implement it correctly. Test cases (i.e. examples) didn't find the error because both signing and verification are wrong.

> The generic name component under which the signature value should be nested has an incorrect
length; the length indicates 32 bytes, but there are 36 bytes in that generic name component.

This isn't a bug. `0x09, 0x02, 0x12, 0x00` is not part of the name, but belongs to a separate TLV. It means "Selectors={MustBeFresh=1}" as interpreted as NDN Packet Format v0.2.
