### ISSUE TITLE
esp8266ndn installation issues

### ISSUE THREAD

**Issue by alhail** [yoursunny/esp8266ndn#2]
I am very interested to run the NDN on ESP32 and have seen that you already have implemented it.

After cloning the "NDNph" and the esp8266ndn examples form GIT flowing the steps here "https://github.com/yoursunny/esp8266ndn", I am now trying to run your code but I have some issues regarding the installation the esp8266ndn on my board. I would like to use the ESP32 Dev board.

The project example "PingClient" from yoursunny/esp8266ndn/\examples does not find the library with the name "esp8266ndn". I am getting the error "PingClient:8:24: fatal error: 
esp8266ndn.h: No such file or directory".

Can you please help my with this error? Is there something which I should do before I start the installation?

Best wishes

Mohamed

**Comment by yoursunny** [comment]
Are you using Arduino IDE or Arduino CLI? What version?

What operating system are you using?

Where did you clone the NDNph and esp8266ndn repositories?
The `$HOME/Arduino/libraries` path given in README is for Linux.
If you are on Windows, it should be something like `C:\Users\sunny\Documents\Arduino\libraries`.

**Comment by alhail** [comment]
I am using the Arduino IDE under Windows. I have cloned the NDNph to the ..\Arduino\libraries and the esp8266ndn to other place on my laptop ..\Documents\esp-projects.
I faced the problem, maybe I should clone both projects to the same folder ..\Ardunio\libraries, is that correct?

**Comment by yoursunny** [comment]
Both NDNph and esp8266ndn must be cloned to `Arduino/libraries/`.
You can put your own program anywhere, but the libraries have to be placed there.

**Comment by alhail** [comment]
yes, thanks for the rapid answer. It works now.

I am interested to cooperate with yout to resrach on NDN and IoT. If you do not mind we can meet and discuss it?
