### ISSUE TITLE
Is it possible to use esp8266ndn as forwarder

### ISSUE THREAD

**Issue by derteufelqwe** [yoursunny/esp8266ndn#4]
Hello,
I was wondering if it's possible that this esp8266ndn library also forwards Interest / Data packets?
Take a look at my setup:
![Setups](https://github.com/yoursunny/esp8266ndn/assets/44213358/8f68932d-997f-4dcb-8d47-244160cdab7c).

The first one is my current setup. All sensors are connected to a NFD instance in a star topology. This way all sensors can communicate with each other.
But is it possible the get the second setup, where only one sensor is connected to the NFD instance and the other sensors use (in this case Sensor 3) as a gateway?
If that's possible how would I configure my ESP32 firmware (using esp8266ndn) to do so?

**Comment by yoursunny** [comment]
NDNph does not yet have a forwarder, but it's technically possible to implement one.
If you are interested in this feature, join the upcoming NDN hackathon, and we can make it happen.
Hackathon isn't officially announced yet but it will happen in the two days following [NDN Community Meeting 2024](https://www.nist.gov/news-events/events/ndncomm2024).

**Comment by derteufelqwe** [comment]
Thanks for your super quick response. I just wanted to make sure I didn't miss anything.
